name: Continuous Integration - Audit (Rust)

on:
  push:
    paths:
      - ".github/workflows/audit-rust.yml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  pull_request:
    paths:
      - ".github/workflows/audit-rust.yml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  audit-rust:
    permissions:
      contents: read
      checks: write
    uses: jaudiger/reusable-workflows/.github/workflows/audit-rust.yml@16364121c482897e29680101ea22b8a3ea472c25
