name: Continuous Integration - Audit (Rust)

on:
  push:
    paths:
      - ".github/workflows/audit-rust.yml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  pull_request:
    paths:
      - ".github/workflows/audit-rust.yml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  audit-rust:
    permissions:
      contents: read
      checks: write
    uses: jaudiger/reusable-workflows/.github/workflows/audit-rust.yml@0fdb4286768192eacc11e2a71d0ef74fcd1c3195
