name: Continuous Deployment

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    uses: jaudiger/reusable-workflows/.github/workflows/deploy-rust-crates-io.yml@8104be620dc861697cf02b53d8fe3119edece0b5
    secrets: inherit
