name: Continuous Deployment

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    uses: jaudiger/reusable-workflows/.github/workflows/deploy-rust-crates-io.yml@0fdb4286768192eacc11e2a71d0ef74fcd1c3195
    secrets: inherit
