name: Continuous Deployment

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    uses: jaudiger/reusable-workflows/.github/workflows/deploy-rust-crates-io.yml@16364121c482897e29680101ea22b8a3ea472c25
    secrets: inherit
