name: Continuous Integration - Static Analysis (Rust)

on:
  push:
    paths:
      - ".github/workflows/static-analysis-rust.yml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/*.rs"
  pull_request:
    paths:
      - ".github/workflows/static-analysis-rust.yml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/*.rs"
  workflow_dispatch:

concurrency:
  group: static-analysis-rust-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  rust-format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install Rust (${{ matrix.toolchain }})
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: "rustfmt"

      - name: Check formatting
        run: cargo fmt --all -- --check

  rust-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install Rust (${{ matrix.toolchain }})
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: "clippy"

      - name: Cache cargo registry + build
        uses: actions/cache@v5.0.5
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            target
          key: rust-static-analysis-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Check linting
        run: cargo clippy --all-targets --all-features -- -D warnings
